### ISSUE TITLE
Deployment Guide/Instructions

### ISSUE THREAD

**Issue by web-gan** [wolfgangmeyers/aibrush-2#1]
Hi! Loving the example website so far.

Would love to see a deployment guide for how you can get the backend/worker up and running with the frontend website. Where do you host the backend/set it up? Would this be deployable to an AWS EC2 instance? Could you provide in-depth documentation for these?

Would be a game changer!

**Comment by wolfgangmeyers** [comment]
Hi, thanks for the feedback. Just so you know, the example site is running on pretty limited hardware that is literally running in my basement - so no guarantees about content being backed up or available in the future. Make sure to save your images :)

I think that for simplification, I can allow the backend to serve up the frontend code so that they can be combined into one deployable unit. Once that is done it should be very simple to put it on AWS, Heroku, or any other platform that provides nodejs and postgres. Do you have a specific need to deploy on AWS? I'd 

The worker process is a little trickier. I have deployed similar worker processes to EC2, but it is expensive to keep on. If you have your own GPUs these can easily be run locally as an offline process.

I'm thinking it would be really cool to have folks able to run their own GPU clusters and rent out rendering power as a service to power something like this.

**Comment by wolfgangmeyers** [comment]
I'll work on making this easy to deploy and provide instructions on it.

**Comment by web-gan** [comment]
Thanks for the update! I would mainly like to get the worker up and running on an EC2 instance so that I can have it run and generate images solely in the cloud. For example, hit the worker EC2 instance from a URL and have that return the image if that makes sense. Sorta like an API running on EC2. Not worried about EC2 cost really as it would just be fun to mess around with and test.

**Comment by wolfgangmeyers** [comment]
Sounds good. I will update this issue when I have a working documented way
to deploy to AWS.

**Comment by web-gan** [comment]
Awesome! Thanks for the info! Looking forward to a solution :)

**Comment by wolfgangmeyers** [comment]
Hi, please have a look at https://github.com/wolfgangmeyers/aibrush-2/blob/main/DEPLOYING-EC2.md - I've walked through this and got it working, let me know if you run into any issues or of anything isn't clear.

**Comment by web-gan** [comment]
Thank you for that! Really appreciate it! 

I think there may be one thing I'm slightly confused on with what I'm trying to do (it's not you, it's me haha). What exactly is the worker? This is the part that actually generates the images from the phrases, correct? And the backend just talks to the worker from the frontend? 

Would it be possible to deploy the worker (if this is the only necessary part to generate an image) to a URL on it's own as an API? For example, `worker.mydomain.com`. This way, you would have a public API that any client can hit (not just the frontend you built). So any client or app could hit `worker.mydomain.com/api/process-image` or something like that to start a new generation. I think this is what you had going on with `https://aibrush.ngrok.io`, but I could be wrong.

**Comment by wolfgangmeyers** [comment]
Good question. You are right that the frontend and the worker send requests and responses through the backend.

For an API, the calls would need to be either synchronous, where the client makes a call and it doesn't return until there is a result, or asynchronous, where the client makes a call that returns almost immediately, and the result is fetched with a later call. From my experience generating images using vqgan+clip (and every other neural net setup), it usually takes a few or several minutes to develop a good image, which would mean you'd probably want an async api.

The worker could be refactored to provide its own api, but it would limit you to using one GPU. With the backend queue system I've designed with AIBrush, you can have many workers that can pull off the queue and run in parallel. If you'd like to have a simple worker api that you can deploy, I can easily spin off another project based on this one that would meet your needs. In that case, would you want any kind of authentication set up, or would IP whitelisting be good enough?

**Comment by web-gan** [comment]
That would be awesome! I have a backend setup of my own with some auth stuff and a queue system using AWS SQS. I think just let it auth-free and I should be able to tweak it some to my own system's needs if that makes sense.

**Comment by web-gan** [comment]
Rather than storing the images on the server itself, I was going to have them all upload to my S3 bucket. I can figure that out though!

**Comment by wolfgangmeyers** [comment]
Before I build the API, I need to clarify what you're expecting. Right now, the worker pulls off the queue, and then regularly updates the image while it's running. The simplest way to implement this would be a done/not done async api that returns image data when it's done.

Are you going to want to get the image data in intermediate states, or do you just want to see the image after it's finished? Do you want to be able to generate timelapse videos?

**Comment by web-gan** [comment]
So what I'm thinking overall is:
- My system adds a new image request to my SQS queue - when it does this, it sends a request to the worker queue at the public URL. My system generates a UUID for the image ahead of time. all of the data is sent over to the worker. (nothing needs done on this side as everything is handled on mine)
- The worker API starts generating the images and adds them to a S3 bucket using that UUID. The ultimate file location would be BUCKET/IMAGE_UUID/{everything relevant to the generation of that image}. So if the steps are stored from the worker, they would be saved in S3 like so: BUCKET/UUID/001.png, BUCKET/UUID/002.png etc. with the final iteration being the image UUID.png in that folder.
- My API/backend would periodically check that S3 bucket for the completed image file so nothing would need to be done on the actual worker.
- Once my API notices that there is the completed file in the S3 bucket, it would mark that queue message as complete and kick off another job by sending a request to the worker again

**Comment by wolfgangmeyers** [comment]
Sounds easy enough. In this case, the worker will only need to save the file to S3 once. Steps are only needed if you want to see it developing in realtime or create a timelapse video, and they also slow down the process quite a bit - so I'll leave that out.

**Comment by wolfgangmeyers** [comment]
For deployment the steps to set up the EC2 box will be pretty much identical, you can ignore anything related to frontend/backend or nodejs and just follow the worker setup.

**Comment by web-gan** [comment]
Awesome, thank you!

**Comment by wolfgangmeyers** [comment]
Have a look at https://github.com/wolfgangmeyers/aibrush-2/blob/main/worker/server.py

This should be pretty close to what you're looking for.

**Comment by web-gan** [comment]
That's incredible!! Thank you so much!! Would I need to pull down the entire repo again, or can I just place the worker stuff in a folder on the server in `/home/ubuntu/`?

**Comment by wolfgangmeyers** [comment]
Only the worker folder is needed.
