### ISSUE TITLE
two question, config.ts and postgre

### ISSUE THREAD

**Issue by skyheros001** [wolfgangmeyers/aibrush-2#44]
Can you provide the required environment variables for 'config.ts' in the 'backend' folder? Also, I couldn't find the complete structure of PostgreSQL data. ：）

**Comment by wolfgangmeyers** [comment]
I honestly haven't run the backend locally for quite a while. I could write instructions on how to set up the backend, but I plan to completely remove the backend codebase soon and make the frontend work completely with the AI horde. This will greatly simplify things and make them cheaper to run. I think you should be able to run the frontend locally and have it connect to the backend running at https://www.aibrush.art.

**Comment by wolfgangmeyers** [comment]
AiBrush is now a pure frontend, so closing this.
